services:
  db:
    image: postgres
    container_name: memorix-db
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-memorix}
    networks:
      - memorix-network
    env_file:
      - .env
  cache:
    image: redis
    container_name: memorix-cache
    ports:
      - ${CACHE_PORT:-6379}:6379
    environment:
      REDIS_PASSWORD: ${CACHE_PASSWORD:-root}
      REDIS_USERNAME: ${CACHE_USERNAME:-root}
      REDIS_DB: ${CACHE_DB:-0}
    env_file:
      - .env
    networks:
      - memorix-network
  minio:
    image: quay.io/minio/minio
    container_name: memorix-minio
    ports:
      - ${MINIO_PORT:-9000}:9000
      - ${MINIO_CONSOLE_PORT:-9001}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-root}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-rootadmin}
    volumes:
      - minio-data:/data
    networks:
      - memorix-network
    env_file:
      - .env
    command: server /data --console-address ":${MINIO_CONSOLE_PORT:-9001}"
networks:
  memorix-network:
    driver: bridge
    name: memorix-network

volumes:
  minio-data:
    name: minio-data
    driver: local