services:
  db:
    image: postgres
    container_name: memorix-db
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
  cache:
    image: redis
    container_name: memorix-cache
    ports:
      - ${CACHE_PORT}:6379
    environment:
      REDIS_PASSWORD: ${CACHE_PASSWORD}
      REDIS_USERNAME: ${CACHE_USERNAME}
      REDIS_DB: ${CACHE_DB}
    env_file:
      - .env