spring:
  application:
    name: @project.name@
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:${DB_TYPE:postgresql}://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:memorix}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD}
  cache:
    type: ${CACHE_TYPE:redis}
  data:
    redis:
      database: ${CACHE_DB:0}
      host: ${CACHE_HOST:localhost}
      port: ${CACHE_PORT:6379}
      password: ${CACHE_PASSWORD}
      username: ${CACHE_USERNAME:root}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

minio:
  url: ${MINIO_URL:http://localhost:9000}
  root-user: ${MINIO_ROOT_USER:root}
  root-password: ${MINIO_ROOT_PASSWORD}
  default-bucket: ${MINIO_DEFAULT_BUCKET:memorix}

memorix:
  security:
    jwt:
      private-key:
        location: file:${PRIVATE_KEY_LOCATION:.keys/private.pem}
      public-key:
        location: file:${PUBLIC_KEY_LOCATION:.keys/public.pem}
      issuer: ${ISSUER:localhost}
      audience: ${AUDIENCE:memorix}
    access-token:
      lifespan: ${ACCESS_TOKEN_LIFESPAN:15m}
    refresh-token:
      lifespan: ${REFRESH_TOKEN_LIFESPAN:30d}
    action-token:
      lifespan: ${ACTION_TOKEN_LIFESPAN:1h}
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
      allowed-methods: ${CORS_ALLOWED_METHODS:*}
  version: v@project.version@
  frontend:
    verify-email:
      url: ${FRONTEND_VERIFY_EMAIL_URL:http://localhost:4200/verify-email}
    reset-password:
      url: ${FRONTEND_RESET_PASSWORD_URL:http://localhost:4200/reset-password}