spring.profiles.active=dev
spring.config.import=optional:file:.env[.properties]

memorix.rsa.public.key.path=${RSA_PUBLIC_KEY_PATH:file:./keys/public.key}
memorix.rsa.private.key.path=${RSA_PRIVATE_KEY_PATH:file:./keys/private.key}
memorix.jwt.access.token.expiry=${ACCESS_TOKEN_EXPIRY:15m}
memorix.jwt.refresh.token.expiry=${REFRESH_TOKEN_EXPIRY:30d}