spring:
  application:
    name: @project.name@
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:${DB_TYPE}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  cache:
    type: ${CACHE_TYPE}
  data:
    redis:
      database: ${CACHE_DB}
      host: ${CACHE_HOST}
      port: ${CACHE_PORT}
      password: ${CACHE_PASSWORD}
      username: ${CACHE_USERNAME}

memorix:
  security:
    jwt:
      public-key:
        location: file:${RSA_PUBLIC_KEY_LOCATION}
      private-key:
        location: file:${RSA_PRIVATE_KEY_LOCATION}
      access-token:
        expires-in: ${ACCESS_TOKEN_EXPIRES_IN:15m}
      refresh-token:
        expires-in: ${REFRESH_TOKEN_EXPIRES_IN:1d}
      issuer: ${JWT_ISSUER:localhost}
      audience: ${JWT_AUDIENCE:memorix}