spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  application:
    name: @project.artifactId@
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences:
          - ${token.jwt.audience}
          issuer-uri: ${token.jwt.issuer}

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:memorix}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH:true}
          starttls:
            enable: ${SMTP_TLS:true}

rsa:
  public-key:
    path: file:${RSA_PUBLIC_KEY_PATH}
  private-key:
    path: file:${RSA_PRIVATE_KEY_PATH}
  
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
  allowed-methods: ${CORS_ALLOWED_METHODS:*}

token:
  jwt:
    access-token:
      lifespan: ${JWT_ACCESS_TOKEN_LIFESPAN:15m}
    refresh-token:
      lifespan: ${JWT_REFRESH_TOKEN_LIFESPAN:1d}
    audience: ${JWT_AUDIENCE:memorix}
    issuer: ${JWT_ISSUER:http://localhost:8080}
  verification:
    lifespan: ${VERIFICATION_TOKEN_LIFESPAN:6h}
  reset-password:
    lifespan: ${RESET_PASSWORD_TOKEN_LIFESPAN:1h}