CREATE TABLE IF NOT EXISTS progresses (
    card_id UUID NOT NULL,
    user_id UUID NOT NULL,
    easiness_factor DOUBLE NOT NULL DEFAULT 2.5,
    repetitions INT NOT NULL DEFAULT 0,
    interval INT NOT NULL DEFAULT 1,
    next_repetition TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_studied TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (card_id, user_id),
    FOREIGN KEY (card_id) REFERENCES cards(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);