insert into users (username, email, email_verified, password_hash, bio, avatar_url, display_name, enabled, id) values ('nfordy0', 'nfordy0@tuttocitta.it', TRUE, '$2a$04$RJRyCyCfBGb4jzScwh.NS.DXf48H3VXYs.vqxlYSJ78xs1xoe6WDK', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'https://robohash.org/odioreprehenderitmolestiae.png?size=500x500&set=set1', 'Nealson Fordy', TRUE, 'e233ea43-aa34-44fe-bf60-cb31e2d0ecd6');
insert into users (username, email, email_verified, password_hash, bio, avatar_url, display_name, enabled, id) values ('kilyinykh1', 'kilyinykh1@usda.gov', TRUE, '$2a$04$pbtSaizlTD0u2.KcRiolYuiBjwUwSUeuhDbWp4k/tP8U2inbjZuYS', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.

Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'https://robohash.org/sequinesciuntexercitationem.png?size=500x500&set=set1', 'Korrie Ilyinykh', TRUE, '1f6cc667-4f46-4776-bc48-492a55f40824');
insert into users (username, email, email_verified, password_hash, bio, avatar_url, display_name, enabled, id) values ('hswindley2', 'hswindley2@w3.org', TRUE, '$2a$04$Zhx0mpNdZDa6Dv/xQ4Xq1eMqDPYcxEA4co/8.3xdG9xoRGDVPG8U.', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'https://robohash.org/officiaperspiciatisqui.png?size=500x500&set=set1', 'Henryetta Swindley', TRUE, 'b2aceb22-8599-486b-87f2-79ec9be5fa78');
insert into users (username, email, email_verified, password_hash, bio, avatar_url, display_name, enabled, id) values ('atocqueville3', 'atocqueville3@a8.net', TRUE, '$2a$04$FjPjaGxmWlSHantgeEYocu2AopNcdLQ2945IyhYxvBXFCwaa7AuAO', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'https://robohash.org/utmaioresminima.png?size=500x500&set=set1', 'Amie Tocqueville', TRUE, '2a414b02-83c5-489d-92f3-a010968c92a1');
insert into users (username, email, email_verified, password_hash, bio, avatar_url, display_name, enabled, id) values ('dsynke4', 'dsynke4@guardian.co.uk', TRUE, '$2a$04$LRLvi9gy3MuZY1PossES9.H/5ZUSnf38eQ53MilqfPTDGNQeSz/gy', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'https://robohash.org/debitisofficiaex.png?size=500x500&set=set1', 'Dot Synke', TRUE, 'cf0d7ebd-c585-40ab-8591-8c8956b76609');
insert into users (username, email, email_verified, password_hash, bio, avatar_url, display_name, enabled, id) values ('garbon5', 'garbon5@meetup.com', TRUE, '$2a$04$UJLVa26tig4lobUjLw9Lg.0JFvN3mx08nFaklvIXtiHyj9DvY1Qly', null, 'https://robohash.org/doloremaliasmolestiae.png?size=500x500&set=set1', 'Gerhardine Arbon', TRUE, '10178d19-15ee-421f-80bd-256e1b0dfd19');
insert into users (username, email, email_verified, password_hash, bio, avatar_url, display_name, enabled, id) values ('jmcalpin6', 'jmcalpin6@shop-pro.jp', TRUE, '$2a$04$I6TgAlBRr1FbeKwJQzixuufwkD9P6RUyase1.OaU0pWBETCwoMX1C', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'https://robohash.org/nemotemporenisi.png?size=500x500&set=set1', 'Janis McAlpin', TRUE, 'af060ec2-e5bb-4af4-b8f2-71f0ade0bf72');
insert into users (username, email, email_verified, password_hash, bio, avatar_url, display_name, enabled, id) values ('egodbold7', 'egodbold7@1und1.de', TRUE, '$2a$04$hRzNkuPOV2JVAmnmOlui4OgRoUD5Zoj7doU/GGhAjMJOAyZHmx.KS', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'https://robohash.org/anonporro.png?size=500x500&set=set1', 'Emeline Godbold', TRUE, 'afdc9f16-5b51-45eb-be6f-e802736dbf01');
insert into users (username, email, email_verified, password_hash, bio, avatar_url, display_name, enabled, id) values ('acrack8', 'acrack8@springer.com', TRUE, '$2a$04$wgFHHjcnhiD9BitdMDAWBuL7FxpgsyyWYm.IBvKVtT4UhVCCYPkHW', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'https://robohash.org/perspiciatismodiexpedita.png?size=500x500&set=set1', 'Alis Crack', TRUE, '23e41d2c-fedc-4ee8-8cac-2e3b44cfead0');
insert into users (username, email, email_verified, password_hash, bio, avatar_url, display_name, enabled, id) values ('bparysiak9', 'bparysiak9@hubpages.com', TRUE, '$2a$04$kEDyRgLlKx1TU/aYquN7PeVtR1xzTSmf7kjVkonG6AVFxuA5IxkTW', null, 'https://robohash.org/repudiandaeipsamfugiat.png?size=500x500&set=set1', 'Brant Parysiak', TRUE, '95b7a7cb-8433-4189-949c-66aaa7f1ac71');