CREATE TABLE IF NOT EXISTS cards (
    id UUID PRIMARY KEY,
    front TEXT NOT NULL,
    back TEXT NOT NULL,
    deck_id UUID NOT NULL,
    hint TEXT,
    type VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (deck_id) REFERENCES decks(id) ON DELETE CASCADE
);